---

- name: Scaleup
  hosts: localhost
  vars_files:
    - haproxy-autoscale_config.yml
  tasks:
    - name: "Adding server {{instance_id}} {{instance_ip}}"
      lineinfile:
        dest: "{{haproxy_config_file | default('/etc/haproxy/haproxy.cfg')}}"
        state: present
        insertafter: "{{insert_after | default('EOF')}}"
        line: "{{haproxy_config_line}}"
      register: add_result
    - debug:
        msg: "Successfully added server {{instance_id}} {{instance_ip}}"
      when: add_result.changed
