---

- name: Scaleup
  hosts: localhost
  vars:
    instance_ip: ".*"
  vars_files:
    - haproxy-autoscale_config.yml
  tasks:
    - name: "Removing server {{instance_id}}"
      lineinfile:
        dest: "{{haproxy_config_file | default('/etc/haproxy/haproxy.cfg')}}"
        state: absent
        #insertafter: "{{insert_after | default('EOF')}}"
        regexp: "{{haproxy_config_line}}"
      register: add_result
    - debug:
        msg: "Successfully removed server {{instance_id}}"
      when: add_result.changed
    - name: Restart HAProxy
      when: add_result.changed
      register: restart_result
      become: true
      ignore_errors: true
      service:
        name: haproxy
        state: restarted
    - debug:
        msg: "Successfully restarted HAProxy"
      when: restart_result.changed